# Generated by Django 3.2.5 on 2021-08-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicativos',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('pais', models.CharField(
                    choices=[
                        ('(AFEGANISTÃO, 93)', 'AFEGANISTÃO'), ('(ÁFRICA DO SUL, 27)', 'ÁFRICA DO SUL'), ('(ALASKA, 1907)', 'ALASKA'), ('(ALBÂNIA, 355)', 'ALBÂNIA'),
                        ('(ALEMANHA, 49)', 'ALEMANHA'), ('(ANDORRA, 376)', 'ANDORRA'), ('(ANGOLA, 244)', 'ANGOLA'), ('(ANGUILLA, 1264)', 'ANGUILLA'),
                        ('(ANTÍGUA/BARBUDA, 1268)', 'ANTÍGUA/BARBUDA'), ('(ANTILHAS HOLANDESAS, 599)', 'ANTILHAS HOLANDESAS'), ('(ARÁBIA SAUDITA, 966)', 'ARÁBIA SAUDITA'),
                        ('(ARGÉLIA, 213)', 'ARGÉLIA'), ('(ARGENTINA, 54)', 'ARGENTINA'), ('(ARMÉNIA, 374)', 'ARMÉNIA'), ('(ARUBA, 297)', 'ARUBA'),
                        ('(ASCENSÃO, 247)', 'ASCENSÃO'), ('(AUSTRÁLIA, 61)', 'AUSTRÁLIA'), ('(ÁUSTRIA, 43)', 'ÁUSTRIA'), ('(AZERBAIJÃO, 994)', 'AZERBAIJÃO'),
                        ('(BAHAMAS, 1242)', 'BAHAMAS'), ('(BAHREIN, 973)', 'BAHREIN'), ('(BANGLADESH, 880)', 'BANGLADESH'), ('(BARBADOS, 1246)', 'BARBADOS'),
                        ('(BÉLGICA, 32)', 'BÉLGICA'), ('(BELIZE, 501)', 'BELIZE'), ('(BENIN, 229)', 'BENIN'), ('(BERMUDA, 1441)', 'BERMUDA'),
                        ('(BIELORÚSSIA, 375)', 'BIELORÚSSIA'), ('(BOLÍVIA, 591)', 'BOLÍVIA'), ('(BÓSNIA-HERZEGOVINA, 387)', 'BÓSNIA-HERZEGOVINA'),
                        ('(BOTSWANA, 267)', 'BOTSWANA'), ('(BRASIL, 55)', 'BRASIL'), ('(BRUNEI, 673)', 'BRUNEI'), ('(BULGÁRIA, 359)', 'BULGÁRIA'),
                        ('(BURKINA FASO, 226)', 'BURKINA FASO'), ('(BURUNDI, 257)', 'BURUNDI'), ('(BUTÃO, 975)', 'BUTÃO'), ('(CABO VERDE, 238)', 'CABO VERDE'),
                        ('(CAMARÕES, 237)', 'CAMARÕES'), ('(CAMBOJA, 855)', 'CAMBOJA'), ('(CANADÁ, 1)', 'CANADÁ'), ('(CARRIACOU, 1473)', 'CARRIACOU'),
                        ('(CAYMAN, 1345)', 'CAYMAN'), ('(CAZAQUISTÃO, 7)', 'CAZAQUISTÃO'), ('(CHADE, 235)', 'CHADE'), ('(CHILE, 56)', 'CHILE'), ('(CHINA, 86)', 'CHINA'),
                        ('(CHIPRE, 357)', 'CHIPRE'), ('(COLÔMBIA, 57)', 'COLÔMBIA'), ('(COMORES, 269)', 'COMORES'), ('(CONGO, 242)', 'CONGO'), ('(COOK, 682)', 'COOK'),
                        ('(COREIA (REP.DEM.), 850)', 'COREIA (REP.DEM.)'), ('(COREIA DO SUL, 82)', 'COREIA DO SUL'), ('(COSTA DO MARFIM, 225)', 'COSTA DO MARFIM'),
                        ('(COSTA RICA, 506)', 'COSTA RICA'), ('(CROÁCIA, 385)', 'CROÁCIA'), ('(CUBA, 53)', 'CUBA'), ('(DIEGO GARCIA, 246)', 'DIEGO GARCIA'),
                        ('(DIJIBUTI, 253)', 'DIJIBUTI'), ('(DINAMARCA, 45)', 'DINAMARCA'), ('(DOMINICA, 1767)', 'DOMINICA'), ('(EL SALVADOR, 503)', 'EL SALVADOR'),
                        ('(EGIPTO, 20)', 'EGIPTO'), ('(EMIRADOS ÁRAB. UNIDOS, 971)', 'EMIRADOS ÁRAB. UNIDOS'), ('(EQUADOR, 593)', 'EQUADOR'),
                        ('(ERITREIA, 291)', 'ERITREIA'), ('(ESLOVÁQUIA, 421)', 'ESLOVÁQUIA'), ('(ESLOVÉNIA, 386)', 'ESLOVÉNIA'), ('(ESPANHA, 34)', 'ESPANHA'),
                        ('(ESTADOS UNIDOS AMÉRICA, 1)', 'ESTADOS UNIDOS AMÉRICA'), ('(ESTÓNIA, 372)', 'ESTÓNIA'), ('(ETIÓPIA, 251)', 'ETIÓPIA'),
                        ('(FEROE (ILHAS), 298)', 'FEROE (ILHAS)'), ('(FIJI, 679)', 'FIJI'), ('(FILIPINAS, 63)', 'FILIPINAS'), ('(FINLÂNDIA, 358)', 'FINLÂNDIA'),
                        ('(FORMOSA (TAIWAN), 886)', 'FORMOSA (TAIWAN)'), ('(FRANÇA, 33)', 'FRANÇA'), ('(GABÃO, 241)', 'GABÃO'), ('(GÂMBIA, 220)', 'GÂMBIA'),
                        ('(GANA, 233)', 'GANA'), ('(GEÓRGIA, 995)', 'GEÓRGIA'), ('(GIBRALTAR, 350)', 'GIBRALTAR'), ('(GRANADA, 1473)', 'GRANADA'),
                        ('(GRÉCIA, 30)', 'GRÉCIA'), ('(GRONELÂNDIA, 299)', 'GRONELÂNDIA'), ('(GUADALUPE, 590)', 'GUADALUPE'), ('(GUAM, 1671)', 'GUAM'),
                        ('(GUATEMALA, 502)', 'GUATEMALA'), ('(GUIANA, 592)', 'GUIANA'), ('(GUIANA FRANCESA, 594)', 'GUIANA FRANCESA'),
                        ('(GUINÉ-BISSAU, 245)', 'GUINÉ-BISSAU'), ('(GUINÉ-CONACRI, 224)', 'GUINÉ-CONACRI'), ('(GUINÉ EQUATORIAL, 240)', 'GUINÉ EQUATORIAL'),
                        ('(HAITI, 509)', 'HAITI'), ('(HAWAI, 1808)', 'HAWAI'), ('(HOLANDA, 31)', 'HOLANDA'), ('(HONDURAS, 504)', 'HONDURAS'),
                        ('(HONG KONG, 852)', 'HONG KONG'), ('(HUNGRIA, 36)', 'HUNGRIA'), ('(IÉMEN (REP.ÁRABE), 967)', 'IÉMEN (REP.ÁRABE)'), ('(INDIA, 91)', 'INDIA'),
                        ('(INDONÉSIA, 62)', 'INDONÉSIA'), ('(IRÃO, 98)', 'IRÃO'), ('(IRAQUE, 964)', 'IRAQUE'), ('(IRLANDA, 353)', 'IRLANDA'),
                        ('(IRLANDA DO NORTE, 44)', 'IRLANDA DO NORTE'), ('(ISLÂNDIA, 354)', 'ISLÂNDIA'), ('(ISRAEL, 972)', 'ISRAEL'), ('(ITÁLIA, 39)', 'ITÁLIA'),
                        ('(JAMAICA, 1876)', 'JAMAICA'), ('(JAPÃO, 81)', 'JAPÃO'), ('(KOWEIT, 965)', 'KOWEIT'), ('(LAOS, 856)', 'LAOS'), ('(LESOTO, 266)', 'LESOTO'),
                        ('(LETÓNIA, 371)', 'LETÓNIA'), ('(LÍBANO, 961)', 'LÍBANO'), ('(LIBÉRIA, 231)', 'LIBÉRIA'), ('(LÍBIA, 218)', 'LÍBIA'),
                        ('(LIECHTENSTEIN, 423)', 'LIECHTENSTEIN'), ('(LITUÂNIA, 370)', 'LITUÂNIA'), ('(LUXEMBURGO, 352)', 'LUXEMBURGO'), ('(MACAU, 853)', 'MACAU'),
                        ('(MACEDÓNIA, 389)', 'MACEDÓNIA'), ('(MADAGÁSCAR, 261)', 'MADAGÁSCAR'), ('(MALÁSIA, 60)', 'MALÁSIA'), ('(MALAWI, 265)', 'MALAWI'),
                        ('(MALDIVAS, 960)', 'MALDIVAS'), ('(MALI, 223)', 'MALI'), ('(MALTA, 356)', 'MALTA'), ('(MALVINAS/FALKLAND, 500)', 'MALVINAS/FALKLAND'),
                        ('(MARROCOS, 212)', 'MARROCOS'), ('(MARSHALL (ILHAS), 692)', 'MARSHALL (ILHAS)'), ('(MARTINICA, 596)', 'MARTINICA'),
                        ('(MAURÍCIAS, 230)', 'MAURÍCIAS'), ('(MAURITÂNIA, 222)', 'MAURITÂNIA'), ('(MAYOTTE, 269)', 'MAYOTTE'), ('(MÉXICO, 52)', 'MÉXICO'),
                        ('(MICRONÉSIA, 691)', 'MICRONÉSIA'), ('(MOÇAMBIQUE, 258)', 'MOÇAMBIQUE'), ('(MOLDÁVIA, 373)', 'MOLDÁVIA'), ('(MÓNACO, 377)', 'MÓNACO'),
                        ('(MONGÓLIA, 976)', 'MONGÓLIA'), ('(MONTSERRAT, 1664)', 'MONTSERRAT'), ('(MYANMAR (BIRMÂNIA), 95)', 'MYANMAR (BIRMÂNIA)'),
                        ('(NAMÍBIA, 264)', 'NAMÍBIA'), ('(NAURU, 674)', 'NAURU'), ('(NEPAL, 977)', 'NEPAL'), ('(NEVIS, 1869)', 'NEVIS'), ('(NICARÁGUA, 505)', 'NICARÁGUA'),
                        ('(NIGER, 227)', 'NIGER'), ('(NIGÉRIA, 234)', 'NIGÉRIA'), ('(NIUE, 683)', 'NIUE'), ('(NORFOLK, 672)', 'NORFOLK'), ('(NORUEGA, 47)', 'NORUEGA'),
                        ('(NOVA NALEDÓNIA, 687)', 'NOVA NALEDÓNIA'), ('(NOVA ZELÂNDIA, 64)', 'NOVA ZELÂNDIA'), ('(OMÃ, 968)', 'OMÃ'), ('(PALAU, 680)', 'PALAU'),
                        ('(PALESTINA, 970)', 'PALESTINA'), ('(PANAMÁ, 507)', 'PANAMÁ'), ('(PAPUA E NOVA GUINÉ, 675)', 'PAPUA E NOVA GUINÉ'),
                        ('(PAQUISTÃO, 92)', 'PAQUISTÃO'), ('(PARAGUAI, 595)', 'PARAGUAI'), ('(PERU, 51)', 'PERU'), ('(PITCAIRN, 672)', 'PITCAIRN'),
                        ('(POLINÉSIA FRANCESA, 689)', 'POLINÉSIA FRANCESA'), ('(POLÓNIA, 48)', 'POLÓNIA'), ('(PORTO RICO, (1787, 1939))', 'PORTO RICO'),
                        ('(QATAR, 974)', 'QATAR'), ('(QUENIA, 254)', 'QUENIA'), ('(QUIRGUISTÃO, 996)', 'QUIRGUISTÃO'), ('(QUIRIBATI, 686)', 'QUIRIBATI'),
                        ('(REINO UNIDO, 44)', 'REINO UNIDO'), ('(REP.CENTRO AFRICANA, 236)', 'REP.CENTRO AFRICANA'), ('(REPÚBLICA CHECA, 420)', 'REPÚBLICA CHECA'),
                        ('(REP.DEM.CONGO (ZAIRE), 243)', 'REP.DEM.CONGO (ZAIRE)'), ('(REP.DOMINICANA, 1809)', 'REP.DOMINICANA'), ('(REUNIÃO, 262)', 'REUNIÃO'),
                        ('(ROMÉNIA, 40)', 'ROMÉNIA'), ('(RUANDA, 250)', 'RUANDA'), ('(RÚSSIA, 7)', 'RÚSSIA'), ('(S.CRISTOPHE, 1869)', 'S.CRISTOPHE'),
                        ('(S.CROIX, 1340)', 'S.CROIX'), ('(S.HELENA, 290)', 'S.HELENA'), ('(S.JOHN, 1340)', 'S.JOHN'), ('(S.KITTS, 1869)', 'S.KITTS'),
                        ('(S.LUCIA, 1758)', 'S.LUCIA'), ('(S.MARINO, 378)', 'S.MARINO'), ('(S.PIERRE E MIQUELON, 508)', 'S.PIERRE E MIQUELON'),
                        ('(S.THOMAS, 1340)', 'S.THOMAS'), ('(S.TOMÉ E PRÍNCIPE, 239)', 'S.TOMÉ E PRÍNCIPE'), ('(S.VICENTE E GRENADINES, 1784)', 'S.VICENTE E GRENADINES'),
                        ('(SAIPAN (ILHAS MARIANAS), 1670)', 'SAIPAN (ILHAS MARIANAS)'), ('(SALOMÃO, 677)', 'SALOMÃO'), ('(SAMOA AMERICANA, 684)', 'SAMOA AMERICANA'),
                        ('(SAMOA OCIDENTAL, 685)', 'SAMOA OCIDENTAL'), ('(SEICHELES, 248)', 'SEICHELES'), ('(SENEGAL, 221)', 'SENEGAL'),
                        ('(SERRA LEOA, 232)', 'SERRA LEOA'), ('(SÉRVIA E MONTENEGRO, 381)', 'SÉRVIA E MONTENEGRO'), ('(SINGAPURA, 65)', 'SINGAPURA'),
                        ('(SÍRIA, 963)', 'SÍRIA'), ('(SOMÁLIA, 252)', 'SOMÁLIA'), ('(SRI LANKA, 94)', 'SRI LANKA'), ('(SUAZILÂNDIA, 268)', 'SUAZILÂNDIA'),
                        ('(SUDÃO, 249)', 'SUDÃO'), ('(SUÉCIA, 46)', 'SUÉCIA'), ('(SUÍÇA, 41)', 'SUÍÇA'), ('(SURINAME, 597)', 'SURINAME'), ('(TAILÂNDIA, 66)', 'TAILÂNDIA'),
                        ('(TAJIQUISTÃO, 992)', 'TAJIQUISTÃO'), ('(TANZÂNIA, 255)', 'TANZÂNIA'), ('(TIMOR LOROSAE, 670)', 'TIMOR LOROSAE'), ('(TOBAGO, 1868)', 'TOBAGO'),
                        ('(TOGO, 228)', 'TOGO'), ('(TOKELAU, 690)', 'TOKELAU'), ('(TONGA, 676)', 'TONGA'), ('(TORTOLA, 1284)', 'TORTOLA'), ('(TRINDADE, 1868)', 'TRINDADE'),
                        ('(TRISTÃO DA CUNHA, 290)', 'TRISTÃO DA CUNHA'), ('(TUNÍSIA, 216)', 'TUNÍSIA'), ('(TURKS E CAICOS, 1649)', 'TURKS E CAICOS'),
                        ('(TURQUEMENISTÃO, 993)', 'TURQUEMENISTÃO'), ('(TURQUIA, 90)', 'TURQUIA'), ('(TUVALU, 688)', 'TUVALU'), ('(UCRÂNIA, 380)', 'UCRÂNIA'),
                        ('(UGANDA, 256)', 'UGANDA'), ('(URUGUAI, 598)', 'URUGUAI'), ('(USBEQUISTÃO, 998)', 'USBEQUISTÃO'), ('(VANUATU, 678)', 'VANUATU'),
                        ('(VATICANO, 39)', 'VATICANO'), ('(VENEZUELA, 58)', 'VENEZUELA'), ('(VIETNAME, 84)', 'VIETNAME'),
                        ('(VIRGENS AMERICANAS, 1340)', 'VIRGENS AMERICANAS'), ('(VIRGENS BRITÂNICAS, 1284)', 'VIRGENS BRITÂNICAS'),
                        ('(WALLIS E FUTUNA, 681)', 'WALLIS E FUTUNA'), ('(ZÂMBIA, 260)', 'ZÂMBIA'), ('(ZIMBABWE, 263)', 'ZIMBABWE')
                    ],
                    max_length=50,
                    unique=True
                )),
            ],
        ),
    ]
