class GCI:
    def __init__(self):
        self.dados_globais = {
            'AFEGANISTÃO': 93,
            'ÁFRICA DO SUL': 27,
            'ALASKA': 1907,
            'ALBÂNIA': 355,
            'ALEMANHA': 49,
            'ANDORRA': 376,
            'ANGOLA': 244,
            'ANGUILLA': 1264,
            'ANTÍGUA/BARBUDA': 1268,
            'ANTILHAS HOLANDESAS': 599,
            'ARÁBIA SAUDITA': 966,
            'ARGÉLIA': 213,
            'ARGENTINA': 54,
            'ARMÉNIA': 374,
            'ARUBA': 297,
            'ASCENSÃO': 247,
            'AUSTRÁLIA': 61,
            'ÁUSTRIA': 43,
            'AZERBAIJÃO': 994,
            'BAHAMAS': 1242,
            'BAHREIN': 973,
            'BANGLADESH': 880,
            'BARBADOS': 1246,
            'BÉLGICA': 32,
            'BELIZE': 501,
            'BENIN': 229,
            'BERMUDA': 1441,
            'BIELORÚSSIA': 375,
            'BOLÍVIA': 591,
            'BÓSNIA-HERZEGOVINA': 387,
            'BOTSWANA': 267,
            'BRASIL': 55,
            'BRUNEI': 673,
            'BULGÁRIA': 359,
            'BURKINA FASO': 226,
            'BURUNDI': 257,
            'BUTÃO': 975,
            'CABO VERDE': 238,
            'CAMARÕES': 237,
            'CAMBOJA': 855,
            'CANADÁ': 1,
            'CARRIACOU': 1473,
            'CAYMAN': 1345,
            'CAZAQUISTÃO': 7,
            'CHADE': 235,
            'CHILE': 56,
            'CHINA': 86,
            'CHIPRE': 357,
            'COLÔMBIA': 57,
            'COMORES': 269,
            'CONGO': 242,
            'COOK': 682,
            'COREIA (REP.DEM.)': 850,
            'COREIA DO SUL': 82,
            'COSTA DO MARFIM': 225,
            'COSTA RICA': 506,
            'CROÁCIA': 385,
            'CUBA': 53,
            'DIEGO GARCIA': 246,
            'DIJIBUTI': 253,
            'DINAMARCA': 45,
            'DOMINICA': 1767,
            'EL SALVADOR': 503,
            'EGIPTO': 20,
            'EMIRADOS ÁRAB. UNIDOS': 971,
            'EQUADOR': 593,
            'ERITREIA': 291,
            'ESLOVÁQUIA': 421,
            'ESLOVÉNIA': 386,
            'ESPANHA': 34,
            'ESTADOS UNIDOS AMÉRICA': 1,
            'ESTÓNIA': 372,
            'ETIÓPIA': 251,
            'FEROE (ILHAS)': 298,
            'FIJI': 679,
            'FILIPINAS': 63,
            'FINLÂNDIA': 358,
            'FORMOSA (TAIWAN)': 886,
            'FRANÇA': 33,
            'GABÃO': 241,
            'GÂMBIA': 220,
            'GANA': 233,
            'GEÓRGIA': 995,
            'GIBRALTAR': 350,
            'GRANADA': 1473,
            'GRÉCIA': 30,
            'GRONELÂNDIA': 299,
            'GUADALUPE': 590,
            'GUAM': 1671,
            'GUATEMALA': 502,
            'GUIANA': 592,
            'GUIANA FRANCESA': 594,
            'GUINÉ-BISSAU': 245,
            'GUINÉ-CONACRI': 224,
            'GUINÉ EQUATORIAL': 240,
            'HAITI': 509,
            'HAWAI': 1808,
            'HOLANDA': 31,
            'HONDURAS': 504,
            'HONG KONG': 852,
            'HUNGRIA': 36,
            'IÉMEN (REP.ÁRABE)': 967,
            'INDIA': 91,
            'INDONÉSIA': 62,
            'IRÃO': 98,
            'IRAQUE': 964,
            'IRLANDA': 353,
            'IRLANDA DO NORTE': 44,
            'ISLÂNDIA': 354,
            'ISRAEL': 972,
            'ITÁLIA': 39,
            'JAMAICA': 1876,
            'JAPÃO': 81,
            'KOWEIT': 965,
            'LAOS': 856,
            'LESOTO': 266,
            'LETÓNIA': 371,
            'LÍBANO': 961,
            'LIBÉRIA': 231,
            'LÍBIA': 218,
            'LIECHTENSTEIN': 423,
            'LITUÂNIA': 370,
            'LUXEMBURGO': 352,
            'MACAU': 853,
            'MACEDÓNIA': 389,
            'MADAGÁSCAR': 261,
            'MALÁSIA': 60,
            'MALAWI': 265,
            'MALDIVAS': 960,
            'MALI': 223,
            'MALTA': 356,
            'MALVINAS/FALKLAND': 500,
            'MARROCOS': 212,
            'MARSHALL (ILHAS)': 692,
            'MARTINICA': 596,
            'MAURÍCIAS': 230,
            'MAURITÂNIA': 222,
            'MAYOTTE': 269,
            'MÉXICO': 52,
            'MICRONÉSIA': 691,
            'MOÇAMBIQUE': 258,
            'MOLDÁVIA': 373,
            'MÓNACO': 377,
            'MONGÓLIA': 976,
            'MONTSERRAT': 1664,
            'MYANMAR (BIRMÂNIA)': 95,
            'NAMÍBIA': 264,
            'NAURU': 674,
            'NEPAL': 977,
            'NEVIS': 1869,
            'NICARÁGUA': 505,
            'NIGER': 227,
            'NIGÉRIA': 234,
            'NIUE': 683,
            'NORFOLK': 672,
            'NORUEGA': 47,
            'NOVA NALEDÓNIA': 687,
            'NOVA ZELÂNDIA': 64,
            'OMÃ': 968,
            'PALAU': 680,
            'PALESTINA': 970,
            'PANAMÁ': 507,
            'PAPUA E NOVA GUINÉ': 675,
            'PAQUISTÃO': 92,
            'PARAGUAI': 595,
            'PERU': 51,
            'PITCAIRN': 672,
            'POLINÉSIA FRANCESA': 689,
            'POLÓNIA': 48,
            'PORTO RICO': (1787, 1939),
            'QATAR': 974,
            'QUENIA': 254,
            'QUIRGUISTÃO': 996,
            'QUIRIBATI': 686,
            'REINO UNIDO': 44,
            'REP.CENTRO AFRICANA': 236,
            'REPÚBLICA CHECA': 420,
            'REP.DEM.CONGO (ZAIRE)': 243,
            'REP.DOMINICANA': 1809,
            'REUNIÃO': 262,
            'ROMÉNIA': 40,
            'RUANDA': 250,
            'RÚSSIA': 7,
            'S.CRISTOPHE': 1869,
            'S.CROIX': 1340,
            'S.HELENA': 290,
            'S.JOHN': 1340,
            'S.KITTS': 1869,
            'S.LUCIA': 1758,
            'S.MARINO': 378,
            'S.PIERRE E MIQUELON': 508,
            'S.THOMAS': 1340,
            'S.TOMÉ E PRÍNCIPE': 239,
            'S.VICENTE E GRENADINES': 1784,
            'SAIPAN (ILHAS MARIANAS)': 1670,
            'SALOMÃO': 677,
            'SAMOA AMERICANA': 684,
            'SAMOA OCIDENTAL': 685,
            'SEICHELES': 248,
            'SENEGAL': 221,
            'SERRA LEOA': 232,
            'SÉRVIA E MONTENEGRO': 381,
            'SINGAPURA': 65,
            'SÍRIA': 963,
            'SOMÁLIA': 252,
            'SRI LANKA': 94,
            'SUAZILÂNDIA': 268,
            'SUDÃO': 249,
            'SUÉCIA': 46,
            'SUÍÇA': 41,
            'SURINAME': 597,
            'TAILÂNDIA': 66,
            'TAJIQUISTÃO': 992,
            'TANZÂNIA': 255,
            'TIMOR LOROSAE': 670,
            'TOBAGO': 1868,
            'TOGO': 228,
            'TOKELAU': 690,
            'TONGA': 676,
            'TORTOLA': 1284,
            'TRINDADE': 1868,
            'TRISTÃO DA CUNHA': 290,
            'TUNÍSIA': 216,
            'TURKS E CAICOS': 1649,
            'TURQUEMENISTÃO': 993,
            'TURQUIA': 90,
            'TUVALU': 688,
            'UCRÂNIA': 380,
            'UGANDA': 256,
            'URUGUAI': 598,
            'USBEQUISTÃO': 998,
            'VANUATU': 678,
            'VATICANO': 39,
            'VENEZUELA': 58,
            'VIETNAME': 84,
            'VIRGENS AMERICANAS': 1340,
            'VIRGENS BRITÂNICAS': 1284,
            'WALLIS E FUTUNA': 681,
            'ZÂMBIA': 260,
            'ZIMBABWE': 263
        }

    def paises(self):
        paises = []
        for pais in self.dados_globais:
            paises.append(pais)
        return paises

    def indicativos(self):
        indicativos = []
        for pais in self.paises():
            indicativo = self.dados_globais[pais]
            indicativos.append(indicativo)
        return indicativos

    def indicativo_especifico(self, _pais):
        try:
            return f"{_pais}: {self.dados_globais[_pais]}"
        except KeyError:
            return f"nenhum indicativo correspondente a {_pais}, " \
                   f"certifique-se de escrever correctamente o nome do pais!"
